name: Minetopia
version: '${project.version}'
main: nl.cheesydevs.minetopia.Minetopia
api-version: 1.16
authors: [ GameHugo_, patatje ]
description: De all in one Minetopia plugin
website: https://cheesydevs.nl
softdepend: [ Vault, WorldEdit, WorldGuard ]
commands:
  money:
    description: "deleting soon..."
  minetopia:
    description: "The main command of the plugin"
    aliases: [ mt ]
  scoreboard:
    description: "soon..."
