name: Minetopia
version: '${project.version}'
main: nl.cheesydevs.minetopia.Minetopia
api-version: 1.16
authors: [ GameHugo_, patatje ]
description: '${project.description}'
website: '${project.url}'
softdepend: [ Vault, WorldEdit, WorldGuard ]
