# This is a workflow to test/build maven

name: Maven build

on:
  push:
    branches: [ main, early-development, testing ]
  pull_request:
    branches: [ main, early-development, testing ]

jobs:
  build:
    name: Build
    # The operating system that the action will be run on
    runs-on: ubuntu-latest

    # The steps of the action
    steps:
      # Checks the repository so the job can access it
      - name: Step 1 - Checkout
        uses: actions/checkout@v2

      # Sets up the java JDK
      - name: Step 2 - Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      # Builds the maven project
      - name: Step 3 - Build
        run: |
          mvn -B package --file pom.xml
          mkdir staging && cp target/*.jar staging

      # Cache the dependencies for faster build time
      - name: Step 4 - Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
